package Service;

import Security.Security;
import Storage.Storage;

public class PasswordService {
    private Storage storage;
    private Security security;

    public PasswordService() {
        this.storage = new Storage();
        this.security = new Security();
    }

    //reads the password for the account, decrypts it and returns it to the user
    public String getPasswordForAccount(String masterPassword, String account) {
        String encryptedPassword = storage.readTheEncryptedPasswordForAccount(account);
        return security.decryptPassword(masterPassword, encryptedPassword);
    }

    //gets the autogenerated password encrypts it and write it to the file
    public void setNewPasswordForAccount(String account, String password, String masterPassword) {
        String encryptedPassword = security.encryptPassword(masterPassword, password);
        storage.writePasswordToRespectiveAccount(account, encryptedPassword);
    }
}
